// export const BikeBrand =[
//   {"id":1,"name":"Harley‑Davidson","logo":"https://cdnlogo.com/logos/harley-davidson.svg"},
//   {"id":2,"name":"Ducati","logo":"https://static.cdnlogo.com/logos/d/74/ducati.svg"},
//   {"id":3,"name":"BMW","logo":"https://brandlogos.net/wp-content/uploads/2021/05/bmw_logo.svg"},
//   {"id":4,"name":"Yamaha","logo":"https://brandlogos.net/wp-content/uploads/2021/05/yamaha_logo.svg"},
//   {"id":5,"name":"Honda","logo":"https://brandlogos.net/wp-content/uploads/2021/05/honda_logo.svg"},
//   {"id":6,"name":"Suzuki","logo":"https://brandlogos.net/wp-content/uploads/2021/05/suzuki_logo.svg"},
//   {"id":7,"name":"Kawasaki","logo":"https://brandlogos.net/wp-content/uploads/2021/05/kawasaki_logo.svg"},
//   {"id":8,"name":"Triumph","logo":"https://brandlogos.net/wp-content/uploads/2021/05/triumph_logo.svg"},
//   {"id":9,"name":"KTM","logo":"https://brandlogos.net/wp-content/uploads/2021/05/ktm_logo.svg"},
//   {"id":10,"name":"Indian Motorcycle","logo":"https://brandlogos.net/wp-content/uploads/2021/05/indian_logo.svg"},
//   {"id":11,"name":"Moto Guzzi","logo":"https://brandlogos.net/wp-content/uploads/2021/05/motoguzzi_logo.svg"},
//   {"id":12,"name":"Aprilia","logo":"https://brandlogos.net/wp-content/uploads/2021/05/aprilia_logo.svg"},
//   {"id":13,"name":"Royal Enfield","logo":"https://brandlogos.net/wp-content/uploads/2021/05/royal-enfield_logo.svg"},
//   {"id":14,"name":"Bajaj","logo":"https://brandlogos.net/wp-content/uploads/2021/05/bajaj_logo.svg"},
//   {"id":15,"name":"Hero MotoCorp","logo":"https://brandlogos.net/wp-content/uploads/2021/05/hero_motocorp_logo.svg"},
//   {"id":16,"name":"TVS","logo":"https://brandlogos.net/wp-content/uploads/2021/05/tvs_logo.svg"},
//   {"id":17,"name":"Zero Motorcycles","logo":"https://brandlogos.net/wp-content/uploads/2021/05/zero_motorcycles_logo.svg"},
//   {"id":18,"name":"Bimota","logo":"https://brandlogos.net/wp-content/uploads/2021/05/bimota_logo.svg"},
//   {"id":19,"name":"Benelli","logo":"https://brandlogos.net/wp-content/uploads/2021/05/benelli_logo.svg"},
//   {"id":20,"name":"Buell","logo":"https://brandlogos.net/wp-content/uploads/2021/05/buell_logo.svg"},
//   {"id":21,"name":"Boss Hoss","logo":"https://brandlogos.net/wp-content/uploads/2021/05/boss_hoss_logo.svg"},
//   {"id":22,"name":"AJS","logo":"https://brandlogos.net/wp-content/uploads/2021/05/ajs_logo.svg"},
//   {"id":23,"name":"Alta Motors","logo":"https://brandlogos.net/wp-content/uploads/2021/05/alta_motors_logo.svg"},
//   {"id":24,"name":"Husqvarna","logo":"https://brandlogos.net/wp-content/uploads/2021/05/husqvarna_logo.svg"},
//   {"id":25,"name":"Husaberg","logo":"https://brandlogos.net/wp-content/uploads/2021/05/husaberg_logo.svg"},
//   {"id":26,"name":"Arctic Cat","logo":"https://brandlogos.net/wp-content/uploads/2021/05/arctic_cat_logo.svg"},
//   {"id":27,"name":"Cagiva","logo":"https://brandlogos.net/wp-content/uploads/2021/05/cagiva_logo.svg"},
//   {"id":28,"name":"Derbi","logo":"https://brandlogos.net/wp-content/uploads/2021/05/derbi_logo.svg"},
//   {"id":29,"name":"DKW","logo":"https://brandlogos.net/wp-content/uploads/2021/05/dkw_logo.svg"},
//   {"id":30,"name":"Dnepr","logo":"https://brandlogos.net/wp-content/uploads/2021/05/dnepr_logo.svg"},
//   {"id":31,"name":"Douglas","logo":"https://brandlogos.net/wp-content/uploads/2021/05/douglas_logo.svg"},
//   {"id":32,"name":"Erik Buell Racing","logo":"https://brandlogos.net/wp-content/uploads/2021/05/ebr_logo.svg"},
//   {"id":33,"name":"Garelli","logo":"https://brandlogos.net/wp-content/uploads/2021/05/garelli_logo.svg"},
//   {"id":34,"name":"Irbis","logo":"https://brandlogos.net/wp-content/uploads/2021/05/irbis_logo.svg"},
//   {"id":35,"name":"Italjet","logo":"https://brandlogos.net/wp-content/uploads/2021/05/italjet_logo.svg"},
//   {"id":36,"name":"Jawa","logo":"https://brandlogos.net/wp-content/uploads/2021/05/jawa_logo.svg"},
//   {"id":37,"name":"Junak","logo":"https://brandlogos.net/wp-content/uploads/2021/05/junak_logo.svg"},
//   {"id":38,"name":"Kymco","logo":"https://brandlogos.net/wp-content/uploads/2021/05/kymco_logo.svg"},
//   {"id":39,"name":"Laverda","logo":"https://brandlogos.net/wp-content/uploads/2021/05/laverda_logo.svg"},
//   {"id":40,"name":"Lifan","logo":"https://brandlogos.net/wp-content/uploads/2021/05/lifan_logo.svg"},
//   {"id":41,"name":"Loncin","logo":"https://brandlogos.net/wp-content/uploads/2021/05/loncin_logo.svg"},
//   {"id":42,"name":"Megelli","logo":"https://brandlogos.net/wp-content/uploads/2021/05/megelli_logo.svg"},
//   {"id":43,"name":"Minsk","logo":"https://brandlogos.net/wp-content/uploads/2021/05/minsk_logo.svg"},
//   {"id":44,"name":"Mondial","logo":"https://brandlogos.net/wp-content/uploads/2021/05/mondial_logo.svg"},
//   {"id":45,"name":"Montesa","logo":"https://brandlogos.net/wp-content/uploads/2021/05/montesa_logo.svg"},
//   {"id":46,"name":"MV Agusta","logo":"https://brandlogos.net/wp-content/uploads/2021/05/mv_agusta_logo.svg"},
//   {"id":47,"name":"MZ","logo":"https://brandlogos.net/wp-content/uploads/2021/05/mz_logo.svg"},
//   {"id":48,"name":"Norton","logo":"https://brandlogos.net/wp-content/uploads/2021/05/norton_logo.svg"},
//   {"id":49,"name":"Ossa","logo":"https://brandlogos.net/wp-content/uploads/2021/05/ossa_logo.svg"},
//   {"id":50,"name":"Piaggio","logo":"https://brandlogos.net/wp-content/uploads/2021/05/piaggio_logo.svg"},
//   {"id":51,"name":"Polaris","logo":"https://brandlogos.net/wp-content/uploads/2021/05/polaris_logo.svg"},
//   {"id":52,"name":"Puch","logo":"https://brandlogos.net/wp-content/uploads/2021/05/puch_logo.svg"},
//   {"id":53,"name":"Rieju","logo":"https://brandlogos.net/wp-content/uploads/2021/05/rieju_logo.svg"},
//   {"id":54,"name":"Razor","logo":"https://brandlogos.net/wp-content/uploads/2021/05/razor_logo.svg"},
//   {"id":55,"name":"Schwinn","logo":"https://brandlogos.net/wp-content/uploads/2021/05/schwinn_logo.svg"},
//   {"id":56,"name":"Simson","logo":"https://brandlogos.net/wp-content/uploads/2021/05/simson_logo.svg"},
//   {"id":57,"name":"SYM","logo":"https://brandlogos.net/wp-content/uploads/2021/05/sym_logo.svg"},
//   {"id":58,"name":"Triton","logo":"https://brandlogos.net/wp-content/uploads/2021/05/triton_logo.svg"},
//   {"id":59,"name":"Ural","logo":"https://brandlogos.net/wp-content/uploads/2021/05/ural_logo.svg"},
//   {"id":60,"name":"Vyrus","logo":"https://brandlogos.net/wp-content/uploads/2021/05/vyrus_logo.svg"},
//   {"id":61,"name":"Zongshen","logo":"https://brandlogos.net/wp-content/uploads/2021/05/zongshen_logo.svg"},
//   {"id":62,"name":"Zündapp","logo":"https://brandlogos.net/wp-content/uploads/2021/05/zundapp_logo.svg"},
//   {"id":63,"name":"Beta","logo":"https://brandlogos.net/wp-content/uploads/2021/05/beta_logo.svg"},
//   {"id":64,"name":"Bultaco","logo":"https://brandlogos.net/wp-content/uploads/2021/05/bultaco_logo.svg"},
//   {"id":65,"name":"Malaguti","logo":"https://brandlogos.net/wp-content/uploads/2021/05/malaguti_logo.svg"},
//   {"id":66,"name":"Polini","logo":"https://brandlogos.net/wp-content/uploads/2021/05/polini_logo.svg"},
//   {"id":67,"name":"Peugeot","logo":"https://brandlogos.net/wp-content/uploads/2021/05/peugeot_logo.svg"},
//   {"id":68,"name":"Mondial","logo":"https://brandlogos.net/wp-content/uploads/2021/05/mondial_logo.svg"},
//   {"id":69,"name":"MV Agusta","logo":"https://brandlogos.net/wp-content/uploads/2021/05/mv_agusta_logo.svg"},
//   {"id":70,"name":"Aprilia","logo":"https://brandlogos.net/wp-content/uploads/2021/05/aprilia_logo.svg"},
//   {"id":71,"name":"Vespa","logo":"https://brandlogos.net/wp-content/uploads/2021/05/vespa_logo.svg"},
//   {"id":72,"name":"Indian","logo":"https://brandlogos.net/wp-content/uploads/2021/05/indian_logo.svg"},
//   {"id":73,"name":"Royal Enfield","logo":"https://brandlogos.net/wp-content/uploads/2021/05/royal-enfield_logo.svg"},
//   {"id":74,"name":"Honda","logo":"https://brandlogos.net/wp-content/uploads/2021/05/honda_logo.svg"},
//   {"id":75,"name":"Yamaha","logo":"https://brandlogos.net/wp-content/uploads/2021/05/yamaha_logo.svg"},
//   {"id":76,"name":"Suzuki","logo":"https://brandlogos.net/wp-content/uploads/2021/05/suzuki_logo.svg"},
//   {"id":77,"name":"Kawasaki","logo":"https://brandlogos.net/wp-content/uploads/2021/05/kawasaki_logo.svg"},
//   {"id":78,"name":"BMW Motorrad","logo":"https://brandlogos.net/wp-content/uploads/2021/05/bmw_logo.svg"},
//   {"id":79,"name":"Harley‑Davidson Motor Company","logo":"https://cdnlogo.com/logos/harley-davidson.svg"},
//   {"id":80,"name":"Zero Motorcycles","logo":"https://brandlogos.net/wp-content/uploads/2021/05/zero_motorcycles_logo.svg"},
//   {"id":81,"name":"KTM","logo":"https://brandlogos.net/wp-content/uploads/2021/05/ktm_logo.svg"},
//   {"id":82,"name":"Triumph","logo":"https://brandlogos.net/wp-content/uploads/2021/05/triumph_logo.svg"},
//   {"id":83,"name":"Ducati","logo":"https://static.cdnlogo.com/logos/d/74/ducati.svg"},
//   {"id":84,"name":"Aprilia","logo":"https://brandlogos.net/wp-content/uploads/2021/05/aprilia_logo.svg"},
//   {"id":85,"name":"Piaggio","logo":"https://brandlogos.net/wp-content/uploads/2021/05/piaggio_logo.svg"},
//   {"id":86,"name":"Vespa","logo":"https://brandlogos.net/wp-content/uploads/2021/05/vespa_logo.svg"},
//   {"id":87,"name":"Royal Enfield","logo":"https://brandlogos.net/wp-content/uploads/2021/05/royal-enfield_logo.svg"},
//   {"id":88,"name":"Hero MotoCorp","logo":"https://brandlogos.net/wp-content/uploads/2021/05/hero_motocorp_logo.svg"},
//   {"id":89,"name":"TVS","logo":"https://brandlogos.net/wp-content/uploads/2021/05/tvs_logo.svg"},
//   {"id":90,"name":"Bajaj","logo":"https://brandlogos.net/wp-content/uploads/2021/05/bajaj_logo.svg"},
//   {"id":91,"name":"Garelli","logo":"https://brandlogos.net/wp-content/uploads/2021/05/garelli_logo.svg"},
//   {"id":92,"name":"Jawa","logo":"https://brandlogos.net/wp-content/uploads/2021/05/jawa_logo.svg"},
//   {"id":93,"name":"MZ","logo":"https://brandlogos.net/wp-content/uploads/2021/05/mz_logo.svg"},
//   {"id":94,"name":"Norton","logo":"https://brandlogos.net/wp-content/uploads/2021/05/norton_logo.svg"},
//   {"id":95,"name":"Simson","logo":"https://brandlogos.net/wp-content/uploads/2021/05/simson_logo.svg"},
//   {"id":96,"name":"Ural","logo":"https://brandlogos.net/wp-content/uploads/2021/05/ural_logo.svg"},
//   {"id":97,"name":"Beta","logo":"https://brandlogos.net/wp-content/uploads/2021/05/beta_logo.svg"},
//   {"id":98,"name":"Bultaco","logo":"https://brandlogos.net/wp-content/uploads/2021/05/bultaco_logo.svg"},
//   {"id":99,"name":"Malaguti","logo":"https://brandlogos.net/wp-content/uploads/2021/05/malaguti_logo.svg"},
//   {"id":100,"name":"Polini","logo":"https://brandlogos.net/wp-content/uploads/2021/05/polini_logo.svg"}
// ]
export const BikeBrand = [
  { id: 1, name: "Harley‑Davidson", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Harley‑Davidson_logo.svg/200px‑Harley‑Davidson_logo.svg.png" },
  { id: 2, name: "Ducati", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Ducati_Logo.svg/200px-Ducati_Logo.svg.png" },
  { id: 3, name: "BMW", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/BMW.svg/200px-BMW.svg.png" },
  { id: 4, name: "Yamaha", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Yamaha_Motor_Logo.svg/200px-Yamaha_Motor_Logo.svg.png" },
  { id: 5, name: "Honda", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Honda-logo.svg/200px-Honda-logo.svg.png" },
  { id: 6, name: "Suzuki", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Suzuki_logo.svg/200px-Suzuki_logo.svg.png" },
  { id: 7, name: "Kawasaki", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Kawasaki_logo.svg/200px-Kawasaki_logo.svg.png" },
  { id: 8, name: "Triumph", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Triumph_Motorcycles_logo.svg/200px-Triumph_Motorcycles_logo.svg.png" },
  { id: 9, name: "KTM", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/KTM-Logo.svg/200px-KTM-Logo.svg.png" },
  { id: 10, name: "Indian Motorcycle", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Indian_Motorcycle_logo.svg/200px-Indian_Motorcycle_logo.svg.png" },
  { id: 11, name: "Royal Enfield", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Royal_Enfield_Logo.svg/200px-Royal_Enfield_Logo.svg.png" },
  { id: 12, name: "Hero MotoCorp", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Hero_MotoCorp_Logo.svg/200px-Hero_MotoCorp_Logo.svg.png" },
  { id: 13, name: "TVS", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/TVS_Motor_Company_Logo.svg/200px-TVS_Motor_Company_Logo.svg.png" },
  { id: 14, name: "Bajaj", logo: "https://www.vecteezy.com/png/19766250-bajaj-logo-png-bajaj-icon-transparent-png" },
  { id: 15, name: "Aprilia", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Aprilia_logo.svg/200px-Aprilia_logo.svg.png" },
  { id: 16, name: "Husqvarna", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Husqvarna_logo.svg/200px-Husqvarna_logo.svg.png" },
  { id: 17, name: "Moto Guzzi", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Moto_Guzzi_logo.svg/200px-Moto_Guzzi_logo.svg.png" },
  { id: 18, name: "Benelli", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Benelli_logo.svg/200px-Benelli_logo.svg.png" },
  { id: 19, name: "MV Agusta", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/MV_Agusta_logo.svg/200px-MV_Agusta_logo.svg.png" },
  { id: 20, name: "Vespa", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Vespa_logo.svg/200px-Vespa_logo.svg.png" },
  { id: 21, name: "Bimota", logo: "https://static.cdnlogo.com/logos/b/22/bimota.svg" },
  { id: 22, name: "Buell", logo: "https://static.cdnlogo.com/logos/b/23/buell.svg" },
  { id: 23, name: "Boss Hoss", logo: "https://static.cdnlogo.com/logos/b/24/boss-hoss.svg" },
  { id: 24, name: "AJS", logo: "https://static.cdnlogo.com/logos/a/25/ajs.svg" },
  { id: 25, name: "Alta Motors", logo: "https://static.cdnlogo.com/logos/a/26/alta-motors.svg" },
  { id: 26, name: "Husaberg", logo: "https://static.cdnlogo.com/logos/h/27/husaberg.svg" },
  { id: 27, name: "Cagiva", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Cagiva_logo.svg/200px-Cagiva_logo.svg.png" },
  { id: 28, name: "Derbi", logo: "https://static.cdnlogo.com/logos/d/29/derbi.svg" },
  { id: 29, name: "DKW", logo: "https://static.cdnlogo.com/logos/d/30/dkw.svg" },
  { id: 30, name: "Dnepr", logo: "https://static.cdnlogo.com/logos/d/31/dnepr.svg" },
  { id: 31, name: "Douglas", logo: "https://static.cdnlogo.com/logos/d/32/douglas.svg" },
  { id: 32, name: "Erik Buell Racing", logo: "https://static.cdnlogo.com/logos/e/33/ebr.svg" },
  { id: 33, name: "Garelli", logo: "https://static.cdnlogo.com/logos/g/34/garelli.svg" },
  { id: 34, name: "Irbis", logo: "https://static.cdnlogo.com/logos/i/35/irbis.svg" },
  { id: 35, name: "Italjet", logo: "https://static.cdnlogo.com/logos/i/36/italjet.svg" },
  { id: 36, name: "Jawa", logo: "https://static.cdnlogo.com/logos/j/37/jawa.svg" },
  { id: 37, name: "Junak", logo: "https://static.cdnlogo.com/logos/j/38/junak.svg" },
  { id: 38, name: "Kymco", logo: "https://static.cdnlogo.com/logos/k/39/kymco.svg" },
  { id: 39, name: "Laverda", logo: "https://static.cdnlogo.com/logos/l/40/laverda.svg" },
  { id: 40, name: "Lifan", logo: "https://static.cdnlogo.com/logos/l/41/lifan.svg" },
  { id: 41, name: "Loncin", logo: "https://static.cdnlogo.com/logos/l/42/loncin.svg" },
  { id: 42, name: "Megelli", logo: "https://static.cdnlogo.com/logos/m/43/megelli.svg" },
  { id: 43, name: "Minsk", logo: "https://static.cdnlogo.com/logos/m/44/minsk.svg" },
  { id: 44, name: "Mondial", logo: "https://static.cdnlogo.com/logos/m/45/mondial.svg" },
  { id: 45, name: "Montesa", logo: "https://static.cdnlogo.com/logos/m/46/montesa.svg" },
  { id: 46, name: "MZ", logo: "https://static.cdnlogo.com/logos/m/47/mz.svg" },
  { id: 47, name: "Norton", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Norton_Motorcycles_logo.svg/200px-Norton_Motorcycles_logo.svg.png" },
  { id: 48, name: "Ossa", logo: "https://static.cdnlogo.com/logos/o/49/ossa.svg" },
  { id: 49, name: "Piaggio", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Piaggio_logo.svg/200px-Piaggio_logo.svg.png" },
  { id: 50, name: "Polaris", logo: "https://static.cdnlogo.com/logos/p/51/polaris.svg" }
];
