
export const BikeBrand = [
  { id: 1, name: "Harley‑Davidson", logo: "harly.png" },
  { id: 2, name: "Ducati", logo: "ducati.png" },
  { id: 3, name: "BMW", logo: "bmw.png" },
  { id: 4, name: "Yamaha", logo: "yamaha.png" },
  { id: 5, name: "Honda", logo: "honda.png" },
  { id: 6, name: "Suzuki", logo: "suzuki.png" },
  { id: 7, name: "Kawasaki", logo: "Kawasaki.png" },
  { id: 8, name: "Triumph", logo: "Triumph.png" },
  { id: 9, name: "KTM", logo: "KTM.png" },
  { id: 10, name: "Indian Motorcycle", logo: "Indian Motorcycle.png" },
  { id: 11, name: "Royal Enfield", logo: "Royal Enfield.png" },
  { id: 12, name: "Hero MotoCorp", logo: "Hero MotoCorp.png" },
  { id: 13, name: "TVS", logo: "tvs.png" },
  { id: 14, name: "Bajaj", logo: "Bajaj.png" },
  { id: 15, name: "Aprilia", logo: "Aprilia.png" },
  { id: 16, name: "Husqvarna", logo: "Husqvarna.png" },
  { id: 17, name: "Moto Guzzi", logo: "Moto Guzzi.png" },
  { id: 18, name: "Benelli", logo: "Benelli.png" },
  { id: 19, name: "MV Agusta", logo: "MV Agusta.png" },
  { id: 20, name: "Vespa", logo: "Vespa.png" },
  { id: 21, name: "Bimota", logo: "Bimota.png" },
  { id: 22, name: "Buell", logo: "Buell.png" },
  { id: 23, name: "Boss Hoss", logo: "Boss Hoss.png" },
  { id: 24, name: "AJS", logo: "AJS.png" },
  { id: 26, name: "Husaberg", logo: "Husaberg.png" },
 { id: 42, name: "Megelli", logo: "Megelli.png" },  { id: 29, name: "DKW", logo: "DKW.png" },
  { id: 30, name: "Dnepr", logo: "Dnepr.png" },
  { id: 32, name: "Erik Buell Racing", logo: "Erik Buell Racing.png" },
   { id: 41, name: "Loncin", logo: "Loncin1.png" },
  { id: 35, name: "Italjet", logo: "Italjet.png" },
  { id: 36, name: "Jawa", logo: "Jawa.png" },
  { id: 38, name: "Kymco", logo: "Kymco.png" },
  { id: 39, name: "Laverda", logo: "Laverda.png" },
  { id: 40, name: "Lifan", logo: "Lifan.png" },
  // { id: 41, name: "Loncin", logo: "Loncin1.png" },
 
  // { id: 44, name: "Mondial", logo: "https://static.cdnlogo.com/logos/m/45/mondial.svg" },
  // { id: 45, name: "Montesa", logo: "https://static.cdnlogo.com/logos/m/46/montesa.svg" },
  // { id: 46, name: "MZ", logo: "https://static.cdnlogo.com/logos/m/47/mz.svg" },
  // { id: 47, name: "Norton", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Norton_Motorcycles_logo.svg/200px-Norton_Motorcycles_logo.svg.png" },
  // { id: 48, name: "Ossa", logo: "https://static.cdnlogo.com/logos/o/49/ossa.svg" },
  // { id: 49, name: "Piaggio", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Piaggio_logo.svg/200px-Piaggio_logo.svg.png" },
  // { id: 50, name: "Polaris", logo: "https://static.cdnlogo.com/logos/p/51/polaris.svg" }
];
